### ISSUE TITLE
Project should move to "Reviewed" tab when rec submitted

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/deprecated-labs-zap-api#218] opened 2019-10-02 14:35 UTC
When an LUP submits their recommendation, we won't auto advance the milestone in CRM. However, the project should be categorized as "Reviewed" in the view. 

We'll need to update the SQL queries so that:
- "To Review" tab = projects w/ the user’s milestone && !reviewed
- "Reviewed" tab = projects w/ the next LUP’s milestone || w/ the user’s milestone && reviewed

(We also might need to update the logic on the show view's top-right box.)

**Comment by allthesignals** [comment] 2019-10-09 20:58
See the computed property hearingsSubmittedOrWaived

**Comment by andycochran** [comment] 2019-10-11 19:14
> "Submit recommendation" button should disappear after rec has been submitted

I do not understand ^this title. If a recommendation has been submitted, the project should not show up on any tabs that have buttons. Perhaps the problem is that when a recommendation is submitted, the project is not getting its status changed. This can be addressed by us automating the advancement of the milestone when the recommendation is submitted OR by the tab logic accounting for where a recommendation has been submitted (putting it in the "Reviewed" tab regardless of the current milestone). 

I will update the title and confirm the business logic with our partner.

**Comment by andycochran** [comment] 2019-10-15 14:25
Confirmed that LUP milestones should not auto-advance. Issue title/description updated accordingly.

**Closed as completed** 2019-11-22 16:18 UTC
Labels: High ROI, User: LUP
